services:
  server:
    build: .
    restart: on-failure
    privileged: true
    environment:
      - PORT=80
      - SERIAL_PORT=${SERIAL_PORT}
      - DISABLE_SERIAL=${DISABLE_SERIAL}
    ports:
      - '80:80'
    volumes:
      - server-data:/var/lib/app
      - /dev:/dev

volumes:
  server-data:
